# Generated by Django 5.0.4 on 2024-05-31 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
