# Generated by Django 5.0.4 on 2024-05-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servico_data_criacao_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(editable=False, max_length=52, unique=True),
        ),
    ]
