# Generated by Django 5.0.4 on 2024-06-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar Válvula do Motor'), ('TO', 'Troca de Óleo'), ('B', 'Balanceamento'), ('LS', 'Limpeza Simples'), ('LC', 'Limpeza Completa')], max_length=3),
        ),
    ]
